# Generated by Django 4.2.11 on 2024-05-07 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('user', '0002_city_country_profile_ssn_alter_profile_email_zipcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcode',
            name='city',
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.zipcode'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='ZipCode',
        ),
    ]
