# Generated by Django 4.2.11 on 2024-05-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_zipcode_city_alter_profile_zipcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='SSN',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_company',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='empty', max_length=120),
            preserve_default=False,
        ),
    ]
