# Generated by Django 4.2.11 on 2024-05-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_profile_ssn_remove_profile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
