# Generated by Django 4.2.11 on 2024-05-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_employee_delete_employees'),
        ('user', '0005_profile_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
