# Generated by Django 4.2.11 on 2024-05-07 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_image', models.CharField(max_length=9999)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=1000)),
                ('date_of_offering', models.DateField()),
                ('application_due_date', models.DateField()),
                ('percentage', models.IntegerField()),
                ('num_of_applicants', models.IntegerField(null=True)),
                ('is_available', models.BooleanField()),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.zipcode')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.jobtype')),
            ],
        ),
    ]
