# Generated by Django 4.2.11 on 2024-05-08 13:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_remove_education_applicant_and_more'),
        ('common', '0002_jobcategory_skillgenre_alter_skills_genre'),
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicant')),
            ],
        ),
        migrations.RenameField(
            model_name='job',
            old_name='type',
            new_name='job_type',
        ),
        migrations.RemoveField(
            model_name='job',
            name='num_of_applicants',
        ),
        migrations.AddField(
            model_name='job',
            name='starting_date',
            field=models.DateField(default=datetime.date(2024, 5, 8)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='hasSkills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.application')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.skills')),
            ],
        ),
        migrations.CreateModel(
            name='hasReferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.application')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.references')),
            ],
        ),
        migrations.CreateModel(
            name='hasExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.application')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.experience')),
            ],
        ),
        migrations.CreateModel(
            name='hasEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.application')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.education')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.job'),
        ),
    ]
