# Generated by Django 4.2.11 on 2024-05-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_jobcategory_skillgenre_alter_skills_genre'),
        ('job', '0002_application_rename_type_job_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='zipcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.zipcode'),
        ),
        migrations.AlterField(
            model_name='job',
            name='address',
            field=models.CharField(default='empty', max_length=100),
            preserve_default=False,
        ),
    ]
