# Generated by Django 4.2.11 on 2024-05-08 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_jobcategory_skillgenre_alter_skills_genre'),
        ('job', '0003_job_zipcode_alter_job_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.jobcategory'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_image',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
