# Generated by Django 4.2.11 on 2024-05-11 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_job_category_alter_job_job_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date_of_offering',
        ),
    ]
