# Generated by Django 4.2.11 on 2024-05-14 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_favoritejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date',
            field=models.DateField(default=datetime.date(2024, 5, 14)),
        ),
    ]
