# Generated by Django 4.2.11 on 2024-05-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_remove_job_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
