# Generated by Django 4.2.11 on 2024-05-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_application_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover_letter',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
