# Generated by Django 4.2.11 on 2024-05-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_company_ssn'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.CharField(default='empty', max_length=9999),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompanyImage',
        ),
    ]
