# Generated by Django 4.2.11 on 2024-05-08 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_jobcategory_skillgenre_alter_skills_genre'),
        ('company', '0004_rename_image_company_logo_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='zipcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.zipcode'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
