# Generated by Django 4.2.11 on 2024-05-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_employee_delete_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cover_image',
            field=models.CharField(blank=True, max_length=9999, null=True),
        ),
    ]
