# Generated by Django 4.2.11 on 2024-05-08 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_jobcategory_skillgenre_alter_skills_genre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0004_remove_education_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='address',
            field=models.CharField(default='empty', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.EmailField(default='empty', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='profile_image',
            field=models.CharField(default='empty', max_length=9999),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicant',
            name='zipcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.zipcode'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phone',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
