# Generated by Django 4.2.11 on 2024-05-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_applicant_address_applicant_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='full_name',
            field=models.CharField(default='vantar nafn', max_length=70),
            preserve_default=False,
        ),
    ]
